/*
 * SPDX-License-Identifier: MIT
 *
 * ZMK kscan driver for Hall Effect keyboards using SN74LV4051A analog
 * multiplexers and GH39FKSW Hall Effect sensors on XIAO nRF52840.
 *
 * Hardware:
 *   - MCU:    Seeed XIAO nRF52840 (nRF52840, SAADC 12-bit)
 *   - Sensor: GH39FKSW x22
 *   - MUX:    SN74LV4051A x3  (8:1 analog mux, shared select lines)
 *   - ADC:    AIN1(P0.03), AIN4(P0.28), AIN5(P0.29)
 *   - SEL:    P1.13(S0), P1.14(S1), P1.15(S2)
 */

#define DT_DRV_COMPAT zmk_kscan_adc_mux

#include <zephyr/device.h>
#include <zephyr/devicetree.h>
#include <zephyr/drivers/kscan.h>
#include <zephyr/drivers/gpio.h>
#include <zephyr/drivers/adc.h>
#include <zephyr/kernel.h>
#include <zephyr/sys/util.h>
#include <zephyr/logging/log.h>
#include <zephyr/pm/device.h>
#include <zephyr/settings/settings.h>
#include <string.h>

#include "he_key_state.h"
#include "zmk_kscan_he_api.h"
#include "zmk_kscan_he_private.h"

LOG_MODULE_DECLARE(zmk, CONFIG_ZMK_LOG_LEVEL);

/* -----------------------------------------------------------------------
 * Distance LUT: maps normalized ADC position (0..255) → distance (0..255)
 *
 * This is a linear identity LUT for initial bring-up.
 * Replace with a logarithmic LUT generated by libhmk/tools/distance_lut.py
 * once real GH39FKSW sensor curves are measured.
 * ----------------------------------------------------------------------- */
static const uint8_t distance_lut[DISTANCE_LUT_SIZE] = {
      0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
     16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
     32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
     48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
     64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
     80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
     96, 97, 98, 99,100,101,102,103,104,105,106,107,108,109,110,111,
    112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,
    128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,
    144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,
    160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,
    176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,
    192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,
    208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,
    224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,
    240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,
};

/* -----------------------------------------------------------------------
 * Macros
 * ----------------------------------------------------------------------- */

/* EMA filter: y = (x + y*(N-1)) / N  where N = 2^EMA_ALPHA_EXP */
#define EMA(new_val, old_val) \
    ((uint16_t)(((uint32_t)(new_val) + \
                 (uint32_t)(old_val) * ((1u << EMA_ALPHA_EXP) - 1u)) \
                >> EMA_ALPHA_EXP))

/* Devicetree instance helpers */
#define INST_NUM_SELECT(n)  DT_INST_PROP_LEN(n, select_gpios)
#define INST_NUM_ADC(n)     DT_INST_PROP_LEN(n, io_channels)
#define INST_NUM_ADDR(n)    (1u << INST_NUM_SELECT(n))
#define INST_NUM_KEYS(n)    DT_INST_PROP(n, num_keys)

/* -----------------------------------------------------------------------
 * Shared helper functions (not per-instance)
 * ----------------------------------------------------------------------- */

/**
 * Convert ADC value to travel distance (0-255) using LUT.
 */
static inline uint8_t adc_to_distance(uint16_t adc,
                                       uint16_t rest,
                                       uint16_t bottom)
{
    if (adc <= rest || rest >= bottom) {
        return 0;
    }
    if (adc >= bottom) {
        return 255;
    }
    uint32_t normalized = (uint32_t)(adc - rest) * (DISTANCE_LUT_SIZE - 1u)
                          / (uint32_t)(bottom - rest);
    return distance_lut[normalized];
}

/**
 * Drive MUX select lines S0-S2 to the given address (0-7).
 * Bit 0 → S0, Bit 1 → S1, Bit 2 → S2.
 */
static void set_mux_address(const struct gpio_dt_spec *sel,
                             uint8_t num_sel,
                             uint8_t addr)
{
    for (uint8_t i = 0; i < num_sel; i++) {
        gpio_pin_set_dt(&sel[i], (addr >> i) & 1u);
    }
}

/* -----------------------------------------------------------------------
 * Public API: device registry and accessor functions
 *
 * The driver uses macro-based per-instance expansion, so we use a vtable
 * registry to bridge between the generic API and instance-specific data.
 * ----------------------------------------------------------------------- */

#define HE_KSCAN_MAX_DEVICES 2

static struct {
    const struct device *dev;
    struct he_kscan_api_vtable vtable;
} he_registry[HE_KSCAN_MAX_DEVICES];
static int he_registry_count = 0;

static struct he_kscan_api_vtable *find_vtable(const struct device *dev) {
    for (int i = 0; i < he_registry_count; i++) {
        if (he_registry[i].dev == dev) {
            return &he_registry[i].vtable;
        }
    }
    return NULL;
}

void zmk_kscan_he_register_device(const struct device *dev,
                                   struct he_kscan_api_vtable *vtable) {
    if (he_registry_count < HE_KSCAN_MAX_DEVICES) {
        he_registry[he_registry_count].dev = dev;
        he_registry[he_registry_count].vtable = *vtable;
        he_registry_count++;
    }
}

int zmk_kscan_he_get_threshold(const struct device *dev, uint8_t key_idx,
                                uint8_t *press_out, uint8_t *release_out) {
    struct he_kscan_api_vtable *vt = find_vtable(dev);
    if (!vt || key_idx >= vt->num_keys || !press_out || !release_out) {
        return -EINVAL;
    }
    *press_out   = vt->press_thresholds[key_idx];
    *release_out = vt->release_thresholds[key_idx];
    return 0;
}

int zmk_kscan_he_set_threshold(const struct device *dev, uint8_t key_idx,
                                uint8_t press, uint8_t release) {
    struct he_kscan_api_vtable *vt = find_vtable(dev);
    if (!vt || key_idx >= vt->num_keys || release >= press) {
        return -EINVAL;
    }
    vt->press_thresholds[key_idx]   = press;
    vt->release_thresholds[key_idx] = release;
    return 0;
}

int zmk_kscan_he_get_adc_raw(const struct device *dev, uint8_t key_idx,
                              uint16_t *adc_out, uint8_t *distance_out) {
    struct he_kscan_api_vtable *vt = find_vtable(dev);
    if (!vt || key_idx >= vt->num_keys) {
        return -EINVAL;
    }
    if (adc_out)      { *adc_out      = vt->keys[key_idx].adc_filtered; }
    if (distance_out) { *distance_out = vt->keys[key_idx].distance; }
    return 0;
}

int zmk_kscan_he_get_calibration(const struct device *dev, uint8_t key_idx,
                                  uint16_t *rest_out, uint16_t *bottom_out) {
    struct he_kscan_api_vtable *vt = find_vtable(dev);
    if (!vt || key_idx >= vt->num_keys) {
        return -EINVAL;
    }
    if (rest_out)   { *rest_out   = vt->keys[key_idx].adc_rest; }
    if (bottom_out) { *bottom_out = vt->keys[key_idx].adc_bottom; }
    return 0;
}

int zmk_kscan_he_get_num_keys(const struct device *dev, uint8_t *num_keys_out) {
    struct he_kscan_api_vtable *vt = find_vtable(dev);
    if (!vt || !num_keys_out) {
        return -EINVAL;
    }
    *num_keys_out = vt->num_keys;
    return 0;
}

int zmk_kscan_he_save_settings(const struct device *dev) {
    struct he_kscan_api_vtable *vt = find_vtable(dev);
    if (!vt) {
        return -EINVAL;
    }
    return vt->save_settings(dev);
}

int zmk_kscan_he_reset_defaults(const struct device *dev) {
    struct he_kscan_api_vtable *vt = find_vtable(dev);
    if (!vt) {
        return -EINVAL;
    }
    return vt->reset_defaults(dev);
}

int zmk_kscan_he_recalibrate(const struct device *dev) {
    struct he_kscan_api_vtable *vt = find_vtable(dev);
    if (!vt) {
        return -EINVAL;
    }
    return vt->recalibrate(dev);
}

/* -----------------------------------------------------------------------
 * Per-instance macro expansion
 * ----------------------------------------------------------------------- */

#define GPIO_SPEC_ENTRY(node, prop, idx)    GPIO_DT_SPEC_GET_BY_IDX(node, prop, idx),
#define ADC_DT_SPEC_ENTRY(node, prop, idx)  ADC_DT_SPEC_GET_BY_IDX(node, idx),

#define KSCAN_ADC_MUX_INST(n)                                                   \
                                                                                \
    /* Static GPIO specs for select lines */                                    \
    static const struct gpio_dt_spec he_select_gpios_##n[] = {                  \
        DT_INST_FOREACH_PROP_ELEM(n, select_gpios, GPIO_SPEC_ENTRY)             \
    };                                                                          \
                                                                                \
    /* Static ADC channel specs */                                              \
    static const struct adc_dt_spec he_adc_channels_##n[] = {                   \
        DT_INST_FOREACH_PROP_ELEM(n, io_channels, ADC_DT_SPEC_ENTRY)            \
    };                                                                          \
                                                                                \
    /* MUX map: flat array [addr*num_adc + adc_idx] → key_index */             \
    static const uint8_t he_mux_map_##n[] = DT_INST_PROP(n, mux_map);          \
                                                                                \
    /* Driver configuration (read-only, from devicetree) */                    \
    struct he_kscan_cfg_##n {                                                   \
        const struct gpio_dt_spec *select_gpios;                                \
        const struct adc_dt_spec  *adc_channels;                               \
        const uint8_t             *mux_map;                                     \
        uint8_t  num_select;                                                    \
        uint8_t  num_adc;                                                       \
        uint8_t  num_addr;                                                      \
        uint8_t  num_keys;                                                      \
        uint16_t scan_period_ms;                                                \
        uint16_t idle_scan_period_ms;                                           \
        uint16_t idle_enter_ms;                                                 \
        uint8_t  idle_wakeup_delta;                                             \
        uint16_t settle_us;                                                     \
        bool     invert_adc;                                                    \
        uint8_t  press_threshold;                                               \
        uint8_t  release_threshold;                                             \
        uint16_t calibration_duration_ms;                                       \
        uint16_t debounce_ms;                                                   \
        uint16_t initial_adc_range;                                             \
        struct gpio_dt_spec sleep_gpio;                                         \
        struct gpio_dt_spec wakeup_gpio;                                        \
        bool has_sleep_gpio;                                                    \
        bool has_wakeup_gpio;                                                   \
    };                                                                          \
                                                                                \
    static const struct he_kscan_cfg_##n he_cfg_##n = {                         \
        .select_gpios          = he_select_gpios_##n,                           \
        .adc_channels          = he_adc_channels_##n,                          \
        .mux_map               = he_mux_map_##n,                                \
        .num_select            = INST_NUM_SELECT(n),                            \
        .num_adc               = INST_NUM_ADC(n),                               \
        .num_addr              = INST_NUM_ADDR(n),                              \
        .num_keys              = INST_NUM_KEYS(n),                              \
        .scan_period_ms        = DT_INST_PROP(n, scan_period_ms),               \
        .idle_scan_period_ms   = DT_INST_PROP_OR(n, idle_scan_period_ms, 12),   \
        .idle_enter_ms         = DT_INST_PROP_OR(n, idle_enter_ms, 120),        \
        .idle_wakeup_delta     = DT_INST_PROP_OR(n, idle_wakeup_delta, 4),      \
        .settle_us             = DT_INST_PROP(n, settle_us),                    \
        .invert_adc            = DT_INST_PROP(n, invert_adc),                   \
        .press_threshold       = DT_INST_PROP(n, press_threshold),              \
        .release_threshold     = DT_INST_PROP(n, release_threshold),            \
        .calibration_duration_ms = DT_INST_PROP(n, calibration_duration_ms),    \
        .debounce_ms             = DT_INST_PROP_OR(n, debounce_ms, 5),         \
        .initial_adc_range       = DT_INST_PROP_OR(n, initial_adc_range, 650), \
        .has_sleep_gpio = DT_INST_NODE_HAS_PROP(n, sleep_gpios),               \
        .sleep_gpio = COND_CODE_1(DT_INST_NODE_HAS_PROP(n, sleep_gpios),       \
            (GPIO_DT_SPEC_INST_GET(n, sleep_gpios)), ({0})),                    \
        .has_wakeup_gpio = DT_INST_NODE_HAS_PROP(n, wakeup_gpios),             \
        .wakeup_gpio = COND_CODE_1(DT_INST_NODE_HAS_PROP(n, wakeup_gpios),     \
            (GPIO_DT_SPEC_INST_GET(n, wakeup_gpios)), ({0})),                   \
    };                                                                          \
                                                                                \
    /* Driver runtime data */                                                   \
    struct he_kscan_data_##n {                                                  \
        const struct device *dev;                                               \
        kscan_callback_t     callback;                                          \
        struct k_work_delayable scan_work;                                      \
        struct he_key_state  keys[INST_NUM_KEYS(n)];                            \
        int16_t              adc_buf[INST_NUM_ADC(n)];                          \
        int64_t              last_activity_ms;                                  \
        bool                 idle_mode;                                         \
        uint32_t             scan_count;                                        \
        uint8_t              press_thresholds[INST_NUM_KEYS(n)];                \
        uint8_t              release_thresholds[INST_NUM_KEYS(n)];              \
    };                                                                          \
                                                                                \
    static struct he_kscan_data_##n he_data_##n;

/* -----------------------------------------------------------------------
 * Per-instance scan / calibration / API functions
 * ----------------------------------------------------------------------- */

#define KSCAN_ADC_MUX_FUNCS(n)                                                  \
                                                                                \
    /* --------------------------------------------------------------- */       \
    /* Scan work handler: runs once per scan_period_ms                  */       \
    /* --------------------------------------------------------------- */       \
    static void he_scan_##n(struct k_work *work)                                \
    {                                                                           \
        struct k_work_delayable *dwork = k_work_delayable_from_work(work);      \
        struct he_kscan_data_##n *data =                                        \
            CONTAINER_OF(dwork, struct he_kscan_data_##n, scan_work);           \
        const struct he_kscan_cfg_##n *cfg = &he_cfg_##n;                       \
        struct adc_sequence seq = { 0 };                                        \
        bool scan_has_activity = false;                                         \
        int64_t now = k_uptime_get();                                           \
                                                                                \
        for (uint8_t addr = 0; addr < cfg->num_addr; addr++) {                  \
            /* 1. Drive MUX address */                                          \
            set_mux_address(cfg->select_gpios, cfg->num_select, addr);          \
                                                                                \
            /* 2. Wait for MUX output to settle */                              \
            k_busy_wait(cfg->settle_us);                                        \
                                                                                \
            /* 3. Read each ADC channel */                                      \
            for (uint8_t ai = 0; ai < cfg->num_adc; ai++) {                     \
                                                                                \
                /* Map slot → key index; skip unused slots */                   \
                uint8_t key_idx = cfg->mux_map[addr * cfg->num_adc + ai];       \
                if (key_idx >= cfg->num_keys) {                                 \
                    continue;                                                   \
                }                                                               \
                                                                                \
                /* ADC read */                                                  \
                (void)adc_sequence_init_dt(&cfg->adc_channels[ai], &seq);       \
                seq.buffer      = &data->adc_buf[ai];                           \
                seq.buffer_size = sizeof(int16_t);                              \
                                                                                \
                if (adc_read_dt(&cfg->adc_channels[ai], &seq) < 0) {           \
                    LOG_ERR("ADC read fail addr=%d ch=%d", addr, ai);           \
                    continue;                                                   \
                }                                                               \
                                                                                \
                /* 4. Apply polarity correction */                              \
                int16_t raw = data->adc_buf[ai];                                \
                if (raw < 0) { raw = 0; }                                       \
                uint16_t adc_val = (uint16_t)raw;                               \
                if (cfg->invert_adc) {                                          \
                    adc_val = ADC_MAX_VALUE - adc_val;                          \
                }                                                               \
                                                                                \
                /* 5. EMA filter */                                             \
                struct he_key_state *ks = &data->keys[key_idx];                 \
                uint16_t prev_filtered = ks->adc_filtered;                      \
                ks->adc_filtered = EMA(adc_val, ks->adc_filtered);              \
                ks->adc_prev_filtered = prev_filtered;                          \
                                                                                \
                uint16_t adc_delta = (ks->adc_filtered >= prev_filtered)        \
                    ? (uint16_t)(ks->adc_filtered - prev_filtered)              \
                    : (uint16_t)(prev_filtered - ks->adc_filtered);             \
                if (adc_delta >= cfg->idle_wakeup_delta) {                      \
                    scan_has_activity = true;                                   \
                }                                                               \
                                                                                \
                /* 6. Track bottom-out (max travel) */                          \
                if (ks->adc_filtered >=                                         \
                    (uint16_t)(ks->adc_bottom + CALIBRATION_EPSILON)) {         \
                    uint16_t old_bottom = ks->adc_bottom;                       \
                    ks->adc_bottom = ks->adc_filtered;                          \
                    /* Log bottom updates for diagnostic keys */                \
                    if (key_idx == 17 || key_idx == 20) {                       \
                        LOG_WRN("key[%d] bottom updated: %u -> %u (filt=%u)",  \
                                key_idx, old_bottom, ks->adc_bottom,            \
                                ks->adc_filtered);                              \
                    }                                                           \
                }                                                               \
                                                                                \
                /* 7. Distance conversion via LUT */                            \
                ks->distance = adc_to_distance(ks->adc_filtered,               \
                                               ks->adc_rest,                    \
                                               ks->adc_bottom);                 \
                                                                                \
                /* 8. Threshold + hysteresis press/release detection      */  \
                /*    with debounce: ignore transitions within debounce_ms */  \
                /*    of the last state change to prevent rapid bouncing.  */  \
                bool was_pressed = ks->pressed;                                 \
                bool want_press = (!ks->pressed &&                              \
                                   ks->distance >= data->press_thresholds[key_idx]); \
                bool want_release = (ks->pressed &&                             \
                                     ks->distance <= data->release_thresholds[key_idx]); \
                                                                                \
                if (want_press || want_release) {                               \
                    int64_t since = now - ks->last_transition_ms;               \
                    if (since >= (int64_t)cfg->debounce_ms) {                   \
                        ks->pressed = want_press;                               \
                        ks->last_transition_ms = now;                           \
                    }                                                           \
                }                                                               \
                                                                                \
                /* 9. Fire callback on state change */                          \
                if (ks->pressed != was_pressed && data->callback) {             \
                    /* VOUT(mV) from inverted 12-bit ADC (gain=1/6, ref=3.6V) */\
                    uint32_t _vout_mv = (uint32_t)(ADC_MAX_VALUE -              \
                        ks->adc_filtered) * 3600u / ADC_MAX_VALUE;              \
                    uint32_t _vrest_mv = (uint32_t)(ADC_MAX_VALUE -             \
                        ks->adc_rest) * 3600u / ADC_MAX_VALUE;                  \
                    /* AWAKE raw state (Mode1: INPUT, should be HIGH always)  */\
                    gpio_port_value_t _wp = 0;                                  \
                    int _awake = -1;                                             \
                    if (cfg->has_wakeup_gpio) {                                 \
                        gpio_port_get_raw(cfg->wakeup_gpio.port, &_wp);         \
                        _awake = (_wp >> cfg->wakeup_gpio.pin) & 1;             \
                    }                                                           \
                    LOG_INF("key %d %s dist=%d vout=%umV rest=%umV AWAKE=%s SLEEP=Low", \
                            key_idx,                                            \
                            ks->pressed ? "press" : "release",                 \
                            ks->distance,                                       \
                            _vout_mv, _vrest_mv,                                \
                            _awake < 0 ? "N/A" : (_awake ? "H" : "L"));         \
                    scan_has_activity = true;                                   \
                    data->callback(data->dev, 0, key_idx, ks->pressed);         \
                }                                                               \
            }                                                                   \
        }                                                                       \
                                                                                \
        if (scan_has_activity) {                                                \
            data->last_activity_ms = now;                                       \
            data->idle_mode = false;                                            \
        } else if (!data->idle_mode &&                                          \
                   (now - data->last_activity_ms) >= cfg->idle_enter_ms) {      \
            data->idle_mode = true;                                             \
        }                                                                       \
                                                                                \
        uint16_t next_period_ms = data->idle_mode                               \
            ? cfg->idle_scan_period_ms                                          \
            : cfg->scan_period_ms;                                              \
                                                                                \
        /* Periodic diagnostic logging (every 250 scans ≈ 1 second at 4ms) */  \
        data->scan_count++;                                                     \
        if (data->scan_count % 250 == 0) {                                      \
            /* Log key 17 (LALT) and key 20 (LCTRL) state */                   \
            if (17 < cfg->num_keys && 20 < cfg->num_keys) {                     \
                LOG_INF("DIAG [%u] k17: filt=%4u rest=%4u bot=%4u dist=%3u p=%d | k20: filt=%4u rest=%4u bot=%4u dist=%3u p=%d", \
                    (uint32_t)(data->scan_count / 250),                         \
                    data->keys[17].adc_filtered, data->keys[17].adc_rest,       \
                    data->keys[17].adc_bottom, data->keys[17].distance,         \
                    data->keys[17].pressed,                                     \
                    data->keys[20].adc_filtered, data->keys[20].adc_rest,       \
                    data->keys[20].adc_bottom, data->keys[20].distance,         \
                    data->keys[20].pressed);                                    \
            }                                                                   \
        }                                                                       \
                                                                                \
        /* Schedule next scan */                                                \
        k_work_reschedule(&data->scan_work, K_MSEC(next_period_ms));            \
    }                                                                           \
                                                                                \
    /* --------------------------------------------------------------- */       \
    /* Calibration: collect rest values for calibration_duration_ms     */       \
    /* Keys must be fully released during this period.                   */      \
    /* --------------------------------------------------------------- */       \
    static void he_calibrate_##n(const struct device *dev)                      \
    {                                                                           \
        struct he_kscan_data_##n *data = dev->data;                             \
        const struct he_kscan_cfg_##n *cfg = dev->config;                       \
        struct adc_sequence seq = { 0 };                                        \
                                                                                \
        /* Initial state: all zeros. We will pick up first readings. */         \
        for (uint8_t k = 0; k < cfg->num_keys; k++) {                           \
            data->keys[k].adc_filtered = 0;                                     \
            data->keys[k].adc_prev_filtered = 0;                                \
            data->keys[k].adc_rest     = 0;                                     \
            data->keys[k].adc_bottom   = 0;                                     \
            data->keys[k].distance     = 0;                                     \
            data->keys[k].pressed      = false;                                 \
            data->keys[k].last_transition_ms = 0;                               \
        }                                                                       \
                                                                                \
        const int64_t deadline = k_uptime_get() +                               \
                                 (int64_t)cfg->calibration_duration_ms;         \
                                                                                \
        while (k_uptime_get() < deadline) {                                     \
            for (uint8_t addr = 0; addr < cfg->num_addr; addr++) {              \
                set_mux_address(cfg->select_gpios, cfg->num_select, addr);      \
                k_busy_wait(cfg->settle_us);                                    \
                                                                                \
                for (uint8_t ai = 0; ai < cfg->num_adc; ai++) {                 \
                    uint8_t key_idx = cfg->mux_map[addr * cfg->num_adc + ai];   \
                    if (key_idx >= cfg->num_keys) { continue; }                 \
                                                                                \
                    (void)adc_sequence_init_dt(&cfg->adc_channels[ai], &seq);   \
                    seq.buffer      = &data->adc_buf[ai];                       \
                    seq.buffer_size = sizeof(int16_t);                          \
                                                                                \
                    if (adc_read_dt(&cfg->adc_channels[ai], &seq) < 0) {        \
                        continue;                                               \
                    }                                                           \
                                                                                \
                    int16_t raw = data->adc_buf[ai];                            \
                    if (raw < 0) { raw = 0; }                                   \
                    uint16_t adc_val = (uint16_t)raw;                           \
                    if (cfg->invert_adc) {                                      \
                        adc_val = ADC_MAX_VALUE - adc_val;                      \
                    }                                                           \
                                                                                \
                    struct he_key_state *ks = &data->keys[key_idx];             \
                    if (ks->adc_rest == 0) {                                    \
                        ks->adc_filtered = adc_val;                             \
                        ks->adc_prev_filtered = adc_val;                        \
                        ks->adc_rest     = adc_val;                             \
                    } else {                                                    \
                        ks->adc_prev_filtered = ks->adc_filtered;               \
                        ks->adc_filtered = EMA(adc_val, ks->adc_filtered);      \
                        /* Follow the signal during calibration window */       \
                        ks->adc_rest = ks->adc_filtered;                        \
                    }                                                           \
                                                                                \
                    ks->adc_bottom = ks->adc_rest + cfg->initial_adc_range;    \
                    if (ks->adc_bottom > ADC_MAX_VALUE) {                       \
                        ks->adc_bottom = ADC_MAX_VALUE;                         \
                    }                                                           \
                }                                                               \
            }                                                                   \
        }                                                                       \
                                                                                \
        LOG_INF("HE20 calibration done.");                                      \
        /* Log all key calibration values for diagnosis */                     \
        for (uint8_t k = 0; k < cfg->num_keys; k++) {                           \
            LOG_INF("  key[%2d] rest=%4u bottom=%4u",                           \
                    k, data->keys[k].adc_rest, data->keys[k].adc_bottom);       \
        }                                                                       \
    }                                                                           \
                                                                                \
    /* --------------------------------------------------------------- */       \
    /* kscan API: configure (set callback)                              */       \
    /* --------------------------------------------------------------- */       \
    static int he_kscan_configure_##n(const struct device *dev,                 \
                                      kscan_callback_t callback)                \
    {                                                                           \
        struct he_kscan_data_##n *data = dev->data;                             \
        if (!callback) { return -EINVAL; }                                      \
        data->callback = callback;                                              \
        return 0;                                                               \
    }                                                                           \
                                                                                \
    /* --------------------------------------------------------------- */       \
    /* kscan API: enable (start scan loop)                              */       \
    /* --------------------------------------------------------------- */       \
    static int he_kscan_enable_##n(const struct device *dev)                    \
    {                                                                           \
        struct he_kscan_data_##n *data = dev->data;                             \
        const struct he_kscan_cfg_##n *cfg = dev->config;                       \
        data->last_activity_ms = k_uptime_get();                                \
        data->idle_mode = false;                                                \
        k_work_reschedule(&data->scan_work, K_MSEC(cfg->scan_period_ms));       \
        return 0;                                                               \
    }                                                                           \
                                                                                \
    /* --------------------------------------------------------------- */       \
    /* kscan API: disable (stop scan loop)                              */       \
    /* --------------------------------------------------------------- */       \
    static int he_kscan_disable_##n(const struct device *dev)                   \
    {                                                                           \
        struct he_kscan_data_##n *data = dev->data;                             \
        k_work_cancel_delayable(&data->scan_work);                              \
        return 0;                                                               \
    }                                                                           \
                                                                                \
    /* --------------------------------------------------------------- */       \
    /* NVS settings: load/save per-key thresholds                       */       \
    /* Blob format: [press_0, release_0, press_1, release_1, ...]       */       \
    /* --------------------------------------------------------------- */       \
    static int he_settings_set_##n(const char *key, size_t len,                 \
                                    settings_read_cb read_cb, void *cb_arg)      \
    {                                                                           \
        struct he_kscan_data_##n *data = &he_data_##n;                          \
        const struct he_kscan_cfg_##n *cfg = &he_cfg_##n;                       \
        const char *next;                                                       \
        if (!settings_name_steq(key, "thresholds", &next) || next) {            \
            return -ENOENT;                                                     \
        }                                                                       \
        uint8_t buf[INST_NUM_KEYS(n) * 2];                                      \
        if (len != sizeof(buf)) {                                               \
            LOG_WRN("he_kscan/%d: thresholds size mismatch "                    \
                    "(got %zu, expected %zu)", n, len, sizeof(buf));             \
            return -EINVAL;                                                     \
        }                                                                       \
        ssize_t rc = read_cb(cb_arg, buf, sizeof(buf));                         \
        if (rc < 0 || (size_t)rc != sizeof(buf)) {                              \
            return 0;                                                           \
        }                                                                       \
        for (uint8_t k = 0; k < cfg->num_keys; k++) {                           \
            uint8_t p = buf[k * 2];                                             \
            uint8_t r = buf[k * 2 + 1];                                         \
            if (p > r && p > 0) {                                               \
                data->press_thresholds[k]   = p;                                \
                data->release_thresholds[k] = r;                                \
            }                                                                   \
        }                                                                       \
        return 0;                                                               \
    }                                                                           \
                                                                                \
    SETTINGS_STATIC_HANDLER_DEFINE(he_kscan_settings_##n,                       \
        "he_kscan/" #n,                                                         \
        NULL,                                                                   \
        he_settings_set_##n,                                                    \
        NULL,                                                                   \
        NULL);                                                                  \
                                                                                \
    static int he_save_settings_##n(const struct device *dev)                   \
    {                                                                           \
        struct he_kscan_data_##n *data = dev->data;                             \
        const struct he_kscan_cfg_##n *cfg = dev->config;                       \
        uint8_t buf[INST_NUM_KEYS(n) * 2];                                      \
        for (uint8_t k = 0; k < cfg->num_keys; k++) {                           \
            buf[k * 2]     = data->press_thresholds[k];                         \
            buf[k * 2 + 1] = data->release_thresholds[k];                       \
        }                                                                       \
        return settings_save_one("he_kscan/" #n "/thresholds",                  \
                                 buf, sizeof(buf));                             \
    }                                                                           \
                                                                                \
    static int he_reset_defaults_##n(const struct device *dev)                  \
    {                                                                           \
        struct he_kscan_data_##n *data = dev->data;                             \
        const struct he_kscan_cfg_##n *cfg = dev->config;                       \
        for (uint8_t k = 0; k < cfg->num_keys; k++) {                           \
            data->press_thresholds[k]   = cfg->press_threshold;                 \
            data->release_thresholds[k] = cfg->release_threshold;               \
        }                                                                       \
        return he_save_settings_##n(dev);                                       \
    }                                                                           \
                                                                                \
    static int he_recalibrate_##n(const struct device *dev)                     \
    {                                                                           \
        struct he_kscan_data_##n *data = dev->data;                             \
        const struct he_kscan_cfg_##n *cfg = dev->config;                       \
        k_work_cancel_delayable(&data->scan_work);                              \
        he_calibrate_##n(dev);                                                  \
        k_work_reschedule(&data->scan_work, K_MSEC(cfg->scan_period_ms));       \
        return 0;                                                               \
    }                                                                           \
                                                                                \
    /* --------------------------------------------------------------- */       \
    /* Device init                                                      */       \
    /* --------------------------------------------------------------- */       \
    static int he_kscan_init_##n(const struct device *dev)                      \
    {                                                                           \
        struct he_kscan_data_##n *data = dev->data;                             \
        const struct he_kscan_cfg_##n *cfg = dev->config;                       \
        int ret;                                                                \
                                                                                \
        data->dev = dev;                                                        \
                                                                                \
        /* Configure MUX select GPIO pins as outputs, default LOW */            \
        for (uint8_t i = 0; i < cfg->num_select; i++) {                         \
            if (!device_is_ready(cfg->select_gpios[i].port)) {                  \
                LOG_ERR("Select GPIO %d port not ready", i);                    \
                return -ENODEV;                                                 \
            }                                                                   \
            ret = gpio_pin_configure_dt(&cfg->select_gpios[i],                  \
                                        GPIO_OUTPUT_LOW);                       \
            if (ret < 0) {                                                      \
                LOG_ERR("Select GPIO %d config failed: %d", i, ret);            \
                return ret;                                                     \
            }                                                                   \
        }                                                                       \
                                                                                \
        /* Set up ADC channels */                                               \
        for (uint8_t i = 0; i < cfg->num_adc; i++) {                            \
            if (!device_is_ready(cfg->adc_channels[i].dev)) {                   \
                LOG_ERR("ADC device for channel %d not ready", i);              \
                return -ENODEV;                                                 \
            }                                                                   \
            ret = adc_channel_setup_dt(&cfg->adc_channels[i]);                  \
            if (ret < 0) {                                                      \
                LOG_ERR("ADC channel %d setup failed: %d", i, ret);             \
                return ret;                                                     \
            }                                                                   \
        }                                                                       \
                                                                                \
        /* SC4823 SLEEP pin: output, default LOW (Mode 1: normal) */             \
        if (cfg->has_sleep_gpio) {                                              \
            if (!device_is_ready(cfg->sleep_gpio.port)) {                       \
                LOG_ERR("Sleep GPIO port not ready");                           \
                return -ENODEV;                                                 \
            }                                                                   \
            gpio_pin_configure_dt(&cfg->sleep_gpio, GPIO_OUTPUT_LOW);           \
        }                                                                       \
                                                                                \
        /* SC4823 AWAKE pin: input with pull-up */                              \
        if (cfg->has_wakeup_gpio) {                                             \
            if (!device_is_ready(cfg->wakeup_gpio.port)) {                      \
                LOG_ERR("Wakeup GPIO port not ready");                          \
                return -ENODEV;                                                 \
            }                                                                   \
            gpio_pin_configure_dt(&cfg->wakeup_gpio, GPIO_INPUT | GPIO_PULL_UP);\
        }                                                                       \
                                                                                \
        /* Initialize scan work item */                                         \
        k_work_init_delayable(&data->scan_work, he_scan_##n);                   \
                                                                                \
        if (cfg->idle_scan_period_ms < cfg->scan_period_ms) {                   \
            LOG_WRN("idle-scan-period-ms(%u) < scan-period-ms(%u)",            \
                cfg->idle_scan_period_ms, cfg->scan_period_ms);             \
        }                                                                       \
                                                                                \
        data->last_activity_ms = k_uptime_get();                                \
        data->idle_mode = false;                                                \
        data->scan_count = 0;                                                   \
                                                                                \
        /* Initialize per-key thresholds from devicetree defaults */            \
        for (uint8_t k = 0; k < cfg->num_keys; k++) {                           \
            data->press_thresholds[k]   = cfg->press_threshold;                 \
            data->release_thresholds[k] = cfg->release_threshold;               \
        }                                                                       \
                                                                                \
        /* Run initial calibration (blocking, ~500ms) */                        \
        he_calibrate_##n(dev);                                                  \
                                                                                \
        /* Register with public API */                                          \
        {                                                                       \
            struct he_kscan_api_vtable _vt = {                                  \
                .num_keys          = cfg->num_keys,                             \
                .default_press     = cfg->press_threshold,                      \
                .default_release   = cfg->release_threshold,                    \
                .press_thresholds  = data->press_thresholds,                    \
                .release_thresholds = data->release_thresholds,                 \
                .keys              = data->keys,                                \
                .save_settings     = he_save_settings_##n,                      \
                .reset_defaults    = he_reset_defaults_##n,                     \
                .recalibrate       = he_recalibrate_##n,                        \
            };                                                                  \
            zmk_kscan_he_register_device(dev, &_vt);                            \
        }                                                                       \
                                                                                \
        LOG_INF("HE20 kscan driver initialized (%d keys) uptime=%lldms",        \
                cfg->num_keys, k_uptime_get());                                 \
        return 0;                                                               \
    }                                                                           \
                                                                                \
    static const struct kscan_driver_api he_kscan_api_##n = {                   \
        .config           = he_kscan_configure_##n,                             \
        .enable_callback  = he_kscan_enable_##n,                                \
        .disable_callback = he_kscan_disable_##n,                               \
    };                                                                          \
                                                                                \
    static int he_kscan_pm_action_##n(const struct device *dev,                 \
                                      enum pm_device_action action)             \
    {                                                                           \
        const struct he_kscan_cfg_##n *cfg = &he_cfg_##n;                       \
        struct he_kscan_data_##n *data = dev->data;                             \
                                                                                \
        switch (action) {                                                       \
        case PM_DEVICE_ACTION_SUSPEND:                                          \
            LOG_INF("HE kscan[" #n "]: suspending");                           \
            k_work_cancel_delayable(&data->scan_work);                          \
            /* SC4823 → Mode 3: SLEEP=HIGH で磁気変化監視モードに移行 */        \
            if (cfg->has_sleep_gpio) {                                          \
                int _ret = gpio_pin_set_dt(&cfg->sleep_gpio, 1);               \
                if (_ret < 0) {                                                 \
                    LOG_WRN("HE kscan[" #n "]: sleep GPIO err: %d "            \
                            "(continuing)", _ret);                             \
                }                                                               \
            }                                                                   \
            /* nRF52840 GPIO SENSE: AWAKE=LOW で System OFF 復帰可能に */       \
            /* SC4823 が Mode 3 へ移行するまで待機 */                           \
            if (cfg->has_sleep_gpio) {                                          \
                k_sleep(K_MSEC(50));                                            \
            }                                                                   \
            if (cfg->has_wakeup_gpio) {                                         \
                /* AWAKE pre-check なし: 常に GPIO SENSE を arm する */         \
                /* SC4823 が Mode 3 移行中に AWAKE を誤アサートする可能性があり  \
                 * pre-check で false positive が発生すると wakeup 不能になる */ \
                int _ret = gpio_pin_interrupt_configure_dt(&cfg->wakeup_gpio,  \
                                                GPIO_INT_LEVEL_LOW);           \
                if (_ret < 0) {                                                 \
                    LOG_WRN("HE kscan[" #n "]: wakeup GPIO err: %d "           \
                            "(continuing)", _ret);                              \
                } else {                                                        \
                    LOG_INF("HE kscan[" #n "]: SENSE armed (GPIO_INT_LEVEL_LOW)");\
                }                                                               \
            }                                                                   \
            return 0;\
                                                                                \
        case PM_DEVICE_ACTION_RESUME:                                           \
            /* wakeup 割り込み解除 */                                            \
            if (cfg->has_wakeup_gpio) {                                         \
                gpio_pin_interrupt_configure_dt(&cfg->wakeup_gpio,              \
                                                GPIO_INT_DISABLE);               \
            }                                                                   \
            /* SC4823 → Mode 1: SLEEP=LOW で通常動作復帰 */                     \
            if (cfg->has_sleep_gpio) {                                          \
                gpio_pin_set_dt(&cfg->sleep_gpio, 0);                           \
                k_sleep(K_MSEC(5));                                             \
            }                                                                   \
            /* Re-calibrate and restart scanning */                             \
            he_calibrate_##n(dev);                                              \
            data->last_activity_ms = k_uptime_get();                            \
            data->idle_mode = false;                                            \
            data->scan_count = 0;                                               \
            k_work_reschedule(&data->scan_work,                                 \
                              K_MSEC(cfg->scan_period_ms));                     \
            LOG_INF("HE kscan[" #n "]: resumed");                              \
            return 0;                                                           \
                                                                                \
        default:                                                                \
            return -ENOTSUP;                                                    \
        }                                                                       \
    }                                                                           \
                                                                                \
                                                                                \
    static int he_awake_pin_test_##n(void) __attribute__((unused));            \
    static int he_awake_pin_test_##n(void)                                      \
    {                                                                           \
        const struct he_kscan_cfg_##n *cfg = &he_cfg_##n;                       \
        struct he_kscan_data_##n *data = &he_data_##n;                          \
        if (!cfg->has_sleep_gpio || !cfg->has_wakeup_gpio) {                    \
            LOG_INF("AWAKE test[" #n "]: no sleep/wakeup GPIOs, skip");         \
            return 0;                                                           \
        }                                                                       \
        const struct device *wport = cfg->wakeup_gpio.port;                     \
        gpio_pin_t wpin = cfg->wakeup_gpio.pin;                                 \
        gpio_port_value_t pval = 0;                                             \
        int port_num = (wport == DEVICE_DT_GET(DT_NODELABEL(gpio1))) ? 1 : 0;  \
                                                                                \
        /* Wait for USB CDC serial console to enumerate */                      \
        k_sleep(K_SECONDS(5));                                                  \
                                                                                \
        LOG_INF("========================================");                    \
        LOG_INF("=== AWAKE PIN (P%d.%02d) TEST START ===", port_num, wpin);    \
        LOG_INF("========================================");                    \
                                                                                \
        /* Stop scan_work so MUX stops switching */                             \
        k_work_cancel_delayable(&data->scan_work);                              \
        k_sleep(K_MSEC(20));                                                    \
        for (uint8_t i = 0; i < cfg->num_select; i++) {                         \
            gpio_pin_set_dt(&cfg->select_gpios[i], 0);                          \
        }                                                                       \
                                                                                \
        /* ---- Phase 1: Mode 1 (SLEEP=Low) ---- */                            \
        /* SC4823 AWAKE pin is INPUT in Mode 1. nRF pull-up drives it. */      \
        /* If LOW here: pin is shorted to GND or wiring problem.       */      \
        gpio_pin_set_dt(&cfg->sleep_gpio, 0);                                   \
        k_sleep(K_MSEC(50));                                                    \
                                                                                \
        LOG_INF("[Phase 1] Mode 1 (SLEEP=Low): reading P%d.%02d for 3s...",    \
                port_num, wpin);                                                 \
        LOG_INF("  SC4823 AWAKE is INPUT in Mode 1 -> expect HIGH (pull-up)"); \
        int ph1_high = 0, ph1_low = 0;                                          \
        for (int i = 0; i < 300; i++) {                                          \
            gpio_port_get_raw(wport, &pval);                                     \
            if ((pval >> wpin) & 1) { ph1_high++; } else { ph1_low++; }         \
            k_sleep(K_MSEC(10));                                                 \
        }                                                                       \
        LOG_INF("[Phase 1] RESULT: HIGH=%d LOW=%d -> %s",                       \
                ph1_high, ph1_low,                                               \
                ph1_low == 0 ? "OK (pin is HIGH)" :                             \
                ph1_high == 0 ? "BAD: pin stuck LOW! wiring issue?" :           \
                "UNSTABLE: floating?");                                          \
                                                                                \
        /* ---- Phase 2: Mode 3 idle (no key press) ---- */                    \
        /* SC4823 monitors VOUT every 12.5ms in Mode 3.                */      \
        /* AWAKE should stay HIGH if no magnet displacement detected.  */      \
        LOG_INF("[Phase 2] Mode 3 (SLEEP=High) idle: DO NOT press keys!");     \
        LOG_INF("  Monitoring P%d.%02d for 5s -> expect HIGH", port_num, wpin);\
        gpio_pin_set_dt(&cfg->sleep_gpio, 1);                                   \
        k_sleep(K_MSEC(100));  /* wait for SC4823 Mode 3 entry */               \
                                                                                \
        int ph2_high = 0, ph2_low = 0;                                          \
        int prev_phys = -1;                                                      \
        for (int i = 0; i < 500; i++) {                                          \
            gpio_port_get_raw(wport, &pval);                                     \
            int cur = (pval >> wpin) & 1;                                       \
            if (cur) { ph2_high++; } else { ph2_low++; }                        \
            if (cur != prev_phys) {                                              \
                LOG_INF("  t=%dms: P%d.%02d -> %s",                             \
                        i * 10, port_num, wpin,                                  \
                        cur ? "HIGH(idle)" : "LOW(AWAKE triggered!)");          \
                prev_phys = cur;                                                 \
            }                                                                   \
            if (i % 100 == 99) {                                                 \
                LOG_INF("  t=%ds: HIGH=%d LOW=%d", (i+1)/100, ph2_high, ph2_low); \
            }                                                                   \
            k_sleep(K_MSEC(10));                                                 \
        }                                                                       \
        LOG_INF("[Phase 2] RESULT: HIGH=%d LOW=%d -> %s",                       \
                ph2_high, ph2_low,                                               \
                ph2_low == 0 ? "OK (HIGH at idle)" :                            \
                ph2_high == 0 ? "BAD: always LOW! sleep wake WILL FAIL" :       \
                "MIXED: intermittent AWAKE trigger");                            \
                                                                                \
        /* ---- Phase 3: Mode 3 with key press ---- */                         \
        /* Stay in Mode 3. User should press a key. AWAKE -> LOW.     */       \
        LOG_INF("[Phase 3] Mode 3: PRESS AND HOLD a key NOW! (5s)");           \
        LOG_INF("  Monitoring P%d.%02d -> expect LOW during press",            \
                port_num, wpin);                                                 \
                                                                                \
        int ph3_high = 0, ph3_low = 0;                                          \
        prev_phys = -1;                                                          \
        for (int i = 0; i < 500; i++) {                                          \
            gpio_port_get_raw(wport, &pval);                                     \
            int cur = (pval >> wpin) & 1;                                       \
            if (cur) { ph3_high++; } else { ph3_low++; }                        \
            if (cur != prev_phys) {                                              \
                LOG_INF("  t=%dms: P%d.%02d -> %s",                             \
                        i * 10, port_num, wpin,                                  \
                        cur ? "HIGH(released)" : "LOW(AWAKE=press!)");          \
                prev_phys = cur;                                                 \
            }                                                                   \
            if (i % 100 == 99) {                                                 \
                LOG_INF("  t=%ds: HIGH=%d LOW=%d", (i+1)/100, ph3_high, ph3_low); \
            }                                                                   \
            k_sleep(K_MSEC(10));                                                 \
        }                                                                       \
        LOG_INF("[Phase 3] RESULT: HIGH=%d LOW=%d -> %s",                       \
                ph3_high, ph3_low,                                               \
                ph3_low > 0 ? "OK (LOW detected = press works)" :              \
                "BAD: never LOW! AWAKE not responding to key press");           \
                                                                                \
        /* Return to Mode 1 */                                                  \
        gpio_pin_set_dt(&cfg->sleep_gpio, 0);                                   \
                                                                                \
        /* ---- Summary ---- */                                                 \
        LOG_INF("========================================");                    \
        LOG_INF("=== AWAKE PIN TEST SUMMARY ===");                             \
        LOG_INF("  Phase 1 Mode1 (SLEEP=Low):  HIGH=%d LOW=%d", ph1_high, ph1_low); \
        LOG_INF("  Phase 2 Mode3 idle:         HIGH=%d LOW=%d", ph2_high, ph2_low); \
        LOG_INF("  Phase 3 Mode3 press:        HIGH=%d LOW=%d", ph3_high, ph3_low); \
                                                                                \
        bool wake_ok = (ph2_low == 0) && (ph3_low > 0);                        \
        if (wake_ok) {                                                          \
            LOG_INF("  >>> SLEEP WAKE: OK - can wake from System OFF");        \
        } else {                                                                \
            LOG_WRN("  >>> SLEEP WAKE: WILL FAIL");                            \
            if (ph1_low > 0) {                                                  \
                LOG_WRN("  P%d.%02d is LOW even in Mode 1:", port_num, wpin);  \
                LOG_WRN("    -> Check wiring: pin may be shorted to GND");     \
                LOG_WRN("    -> Or SC4823 AWAKE is open-drain pulling down");  \
                LOG_WRN("    -> Try external 10k pull-up to 3.3V");            \
            }                                                                   \
            if (ph2_low > 0 && ph1_low == 0) {                                  \
                LOG_WRN("  LOW in Mode 3 idle (no press) = SC4823 issue:");    \
                LOG_WRN("    -> Magnet resting position too close to sensor"); \
                LOG_WRN("    -> SC4823 VOUT baseline shift > 0.4V threshold"); \
                LOG_WRN("    -> If multiple SC4823 share AWAKE, one bad IC");  \
            }                                                                   \
            if (ph3_low == 0) {                                                  \
                LOG_WRN("  Never LOW even when pressing = AWAKE disconnected");\
            }                                                                   \
        }                                                                       \
        LOG_INF("========================================");                    \
                                                                                \
        /* Restart scanning */                                                  \
        k_work_reschedule(&data->scan_work, K_MSEC(cfg->scan_period_ms));       \
        return 0;                                                               \
    }                                                                           \
    PM_DEVICE_DT_INST_DEFINE(n, he_kscan_pm_action_##n);                        \
                                                                                \
    DEVICE_DT_INST_DEFINE(n,                                                    \
                          he_kscan_init_##n,                                    \
                          PM_DEVICE_DT_INST_GET(n),                             \
                          &he_data_##n,                                         \
                          &he_cfg_##n,                                          \
                          POST_KERNEL,                                          \
                          CONFIG_KSCAN_INIT_PRIORITY,                           \
                          &he_kscan_api_##n);

/* -----------------------------------------------------------------------
 * Instantiate driver for every enabled DT node with compatible string
 * ----------------------------------------------------------------------- */

#define KSCAN_ADC_MUX_DEFINE(n) \
    KSCAN_ADC_MUX_INST(n)       \
    KSCAN_ADC_MUX_FUNCS(n)

DT_INST_FOREACH_STATUS_OKAY(KSCAN_ADC_MUX_DEFINE)
